# -*- coding: utf-8 -*-
"""[Baseline_Train]_RandomForest를 활용한 모델 학습 및 피쳐엔지니어링 (학습).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LEpTpDTrqzu6AjBkOkL4v0vzonLUzGed
"""

import os
import zipfile
from google.colab import drive

# 1. 구글 드라이브 마운트
drive.mount('/content/drive')

# 2. 구글 드라이브에 올려둔 open.zip 경로 지정 (본인 드라이브 경로에 맞게 수정)
ZIP_PATH = '/content/drive/MyDrive/LG_Aimers/open.zip'

# 3. 현재 경로(./)에 바로 압축 해제
# open.zip 내부에 이미 'data/' 폴더가 들어있으므로, ./ 에 풀어야 ./data/test.csv 로 올바르게 위치합니다.
if os.path.exists(ZIP_PATH):
    print("압축 해제 중...")
    with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
        zip_ref.extractall('./')
    print("압축 해제 완료!")
else:
    print(f"❌ 경로를 찾을 수 없습니다: {ZIP_PATH}")
    print("구글 드라이브 폴더명과 파일명을 확인해주세요.")

# 4. 파일 정상 존재 여부 확인
if os.path.exists('./data'):
    print("✅ ./data 폴더 내부 파일 목록:", os.listdir('./data'))

"""# [Baseline] RandomForest — 학습

KBO 투구 하나가 **제구 성공** 투구일 확률을 예측하는 베이스라인입니다.

- **입력**: `test.csv` 의 47개 컬럼 (경기 상황, 투수·타자의 직전까지 누적 기록 등)
- **출력**: 제구 성공 확률 (0 이상 1 이하의 실수)
- **평가지표**: Brier Skill Score

`trackman_history.csv` 는 이 베이스라인에서 사용하지 않습니다. 2019~2024 과거 로그
179만 행이 그대로 남아 있으니 직접 활용해 보세요.

이 노트북은 모델을 **학습**하여 `./model/rf.pkl` 로 저장합니다. 저장한 모델은
추론용 `script.py` 와 함께 `baseline_submit.zip` 으로 묶어 제출합니다.

## 1. 라이브러리 불러오기

데이터 처리(pandas)와 모델 학습(scikit-learn)에 필요한 라이브러리를 불러옵니다.
`joblib` 은 학습한 모델을 파일로 저장할 때 사용합니다.
"""

import os
import time

import joblib
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder

DATA_DIR = "./data"

ID = "row_id"
TARGET = "control_success"
CAT_COLS = ["top_bottom", "game_type", "base_state"]

"""## 2. 데이터 불러오기

`train.csv` 는 2019~2024 시즌이고 평가 데이터는 2025 시즌입니다.

사용할 피처 목록은 `test.csv` 가 정합니다. `train.csv` 에만 있는 컬럼을 학습에 넣으면
평가 시점에 그 컬럼이 없어 추론이 실패하기 때문입니다.
"""

test_cols = pd.read_csv(os.path.join(DATA_DIR, "test.csv"),
                        encoding="utf-8-sig", nrows=0).columns
FEATURES = [c for c in test_cols if c != ID]
NUM_COLS = [c for c in FEATURES if c not in CAT_COLS]

train = pd.read_csv(os.path.join(DATA_DIR, "train.csv"),
                    encoding="utf-8-sig", usecols=FEATURES + [TARGET])

print("train:", train.shape, "| 피처:", len(FEATURES),
      f"(범주형 {len(CAT_COLS)}, 수치형 {len(NUM_COLS)})")
print("시즌:", train["season"].min(), "~", train["season"].max())
print(f"제구 성공률: {train[TARGET].mean():.4f}")

"""## 3. 전처리 정의

범주형 3개(`top_bottom`, `game_type`, `base_state`)는 정수로 바꾸고, 수치형 44개의
결측값은 중앙값으로 채웁니다.

두 변환을 `ColumnTransformer` 로 묶어 모델 파이프라인 안에 넣습니다. 이렇게 하면
추론할 때도 같은 변환이 자동으로 따라가므로, 전처리를 빠뜨려 생기는 실수를 막을 수
있습니다. `handle_unknown="use_encoded_value"` 는 학습 때 보지 못한 범주가 평가
데이터에 나타나면 -1 로 처리하라는 뜻입니다.
"""

preprocessor = ColumnTransformer([
    ("cat", OrdinalEncoder(handle_unknown="use_encoded_value",
                           unknown_value=-1), CAT_COLS),
    ("num", SimpleImputer(strategy="median"), NUM_COLS),
])

"""## 4. 모델 정의와 학습

트리 깊이를 10, 잎 노드의 최소 샘플 수를 200으로 제한해 얕게 두었습니다. 학습이
1분 안에 끝나고 모델 파일도 4MB 정도로 가볍습니다. `random_state` 를 고정했고 GPU 를
사용하지 않으므로, 같은 데이터와 같은 패키지 버전이면 어느 환경에서 실행해도 결과가
같습니다.
"""

model = Pipeline([
    ("pre", preprocessor),
    ("clf", RandomForestClassifier(
        n_estimators=100,
        max_depth=10,
        min_samples_leaf=200,
        n_jobs=-1,
        random_state=42,
    )),
])

# 2024 시즌을 검증용으로 떼어 두고 2019~2023 으로 학습합니다.
is_val = train["season"] == 2024
X_train, y_train = train.loc[~is_val, FEATURES], train.loc[~is_val, TARGET]
X_val, y_val = train.loc[is_val, FEATURES], train.loc[is_val, TARGET]
print("train:", len(X_train), "| val:", len(X_val))

t = time.time()
model.fit(X_train, y_train)
print(f"학습 완료 :: {time.time() - t:.1f}s")

"""## 5. 검증 — Brier Skill Score

학습 데이터에서 떼어 둔 2024 시즌으로 검증 점수를 계산합니다.

Brier 는 예측 확률과 실제값(0/1) 차이의 제곱 평균이고, 이를 상수 예측의 Brier 인
`r(1-r)` 로 나누어 Brier Skill Score 를 구합니다. 검증 분할 방식은 참가자가 자유롭게
바꿀 수 있습니다.
"""

val_pred = model.predict_proba(X_val)[:, 1]

r = y_val.mean()
brier = ((val_pred - y_val) ** 2).mean()
baseline_brier = r * (1 - r)
score = max(0, 100000 * (1 - brier / baseline_brier))

print(f"Brier: {brier:.6f} | 기준선 r(1-r): {baseline_brier:.6f}")
print(f"Validation Score: {score:.2f}")

"""## 6. 전체 데이터로 재학습 & 모델 저장

검증으로 성능을 확인했으니 이제 전체 학습 데이터로 다시 학습합니다.

학습한 파이프라인을 `./model/rf.pkl` 로 저장합니다. 이 파일을 추론용 `script.py`,
`requirements.txt` 와 함께 `baseline_submit.zip` 으로 묶으면 제출 준비가 끝납니다.
"""

t = time.time()
model.fit(train[FEATURES], train[TARGET])
print(f"재학습 완료 :: {time.time() - t:.1f}s")

os.makedirs("./model", exist_ok=True)
joblib.dump(model, "./model/rf.pkl", compress=3)
print("저장 완료: ./model/rf.pkl")

"""# [Baseline] RandomForest — 추론

학습 노트북이 저장한 모델(`./model/rf.pkl`)을 불러와 평가 데이터
(`./data/test.csv`)를 예측하고, 제출 파일(`./output/submission.csv`)을 만듭니다.

**코드 제출 방식** — 이 대회는 결과 CSV 가 아니라 코드를 제출합니다. 아래 구조의 zip 을
제출하면 평가 서버가 zip 을 풀고 `script.py` 를 그대로 실행하여 채점합니다.

```
baseline_submit.zip
├── model/
│   └── rf.pkl                # 학습 노트북이 저장한 모델
├── script.py               # 추론 코드 (서버가 실행)
└── requirements.txt        # 필요한 라이브러리
```

이 노트북의 코드 셀을 순서대로 이어 붙인 것이 `script.py` 입니다. 함께 배포된
`[Baseline_Inference]_RandomForest (추론).py` 를 `script.py` 로 이름만 바꿔 넣어도 됩니다.

배포된 `test.csv` 는 제출 형식 확인용 5행 샘플입니다. 실제 평가 데이터 245,789행은
평가 서버에만 있으며, 서버가 같은 경로(`./data/test.csv`)로 넣어 줍니다.

## 1. 라이브러리 불러오기

`pandas` 로 데이터를 읽고 결과를 씁니다. `joblib` 으로 학습 때 저장한 모델(`.pkl`)을
불러옵니다.
"""

import os

import joblib
import pandas as pd

ID_COL = "row_id"
TARGET_COL = "control_success"

"""## 2. 데이터 로드와 전처리

추론 입력은 반드시 **학습 때와 똑같은 방식**으로 만들어야 합니다. 학습에서 `row_id` 만
빼고 나머지 컬럼을 그대로 사용했으므로 여기서도 동일하게 골라냅니다.

범주형 인코딩과 결측 대치는 모델 파일 안의 파이프라인이 함께 수행하므로 이 코드에서는
컬럼만 선택합니다. 파이프라인 밖에서 피처를 만들었다면 그 코드도 여기에 있어야 평가
서버에서 같은 입력이 됩니다.
"""

# =======================
# 데이터 로드 유틸
# =======================

def load_test(path):
    """평가 데이터(csv) 로드. 한 행이 투구 하나."""
    df = pd.read_csv(path, encoding="utf-8-sig")
    if ID_COL not in df.columns:
        raise ValueError(f"test 데이터에 {ID_COL} 컬럼이 없음: {list(df.columns)[:5]}")
    return df


def load_sample_submission(path):
    """sample_submission.csv 로드 — 제출 파일의 row_id 순서/컬럼 기준."""
    df = pd.read_csv(path, encoding="utf-8-sig")
    if list(df.columns[:2]) != [ID_COL, TARGET_COL]:
        raise ValueError(
            f"sample_submission 컬럼이 ({ID_COL}, {TARGET_COL})이 아님: "
            f"{list(df.columns)}")
    return df


# =======================
# 학습 때 사용한 전처리 (그대로)
# =======================

def build_features(df):
    """모델 입력 추출 — 학습 때와 동일하게 row_id만 빼고 전부 사용.

    범주형 인코딩(top_bottom, game_type, base_state)과 결측 대치는
    모델 파일 안의 파이프라인이 함께 수행하므로 여기서는 컬럼만 선택.
    """
    return df.drop(columns=[ID_COL])

"""## 3. 제출 파일 생성 유틸

제출 파일은 `sample_submission.csv` 와 **같은 row_id 순서, 같은 컬럼**이어야 합니다.
모델 예측을 `row_id` 기준으로 `sample_submission` 에 채워 넣습니다. 예측에 없는
`row_id` 는 기존 placeholder 값을 유지합니다.
"""

# =======================
# 제출 파일 생성 유틸
# =======================

def merge_predictions(sub, ids, preds):
    """sample_submission의 row_id 순서에 맞춰 예측 확률 병합.

    예측에 없는 row_id는 sample_submission의 기존 값(placeholder)을 유지.
    """
    pred_map = dict(zip(ids, preds))
    values, n_missing = [], 0
    for rid, cur in zip(sub[ID_COL], sub[TARGET_COL]):
        p = pred_map.get(rid)
        if p is None:
            n_missing += 1
            values.append(cur)
        else:
            values.append(p)
    if n_missing:
        print(f" 경고: 예측이 없어 placeholder를 유지한 row_id {n_missing}건")
    sub[TARGET_COL] = values
    return sub


def save_submission(path, sub):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    sub.to_csv(path, index=False, encoding="utf-8")

"""## 4. 추론 실행

학습 노트북이 저장한 파이프라인을 불러와 평가 데이터를 예측하고
`./output/submission.csv` 를 생성합니다. 파이프라인이 전처리와 분류를 함께 수행하므로
데이터를 그대로 넣으면 됩니다.

`predict_proba(X)[:, 1]` 은 제구 성공(1) 확률입니다. 제출값은 0 이상 1 이하의 실수여야
하므로 0/1 로 반올림하지 않습니다.
"""

# =======================
# main
# =======================

def main():
    # ---- 경로 변수 (필요에 따라 수정) ----
    TEST_DIR = "./data"            # test.csv, sample_submission.csv 위치
    MODEL_DIR = "./model"          # rf.pkl 위치
    OUT_DIR = "./output"
    TEST_PATH = os.path.join(TEST_DIR, "test.csv")
    SAMPLE_SUB_PATH = os.path.join(TEST_DIR, "sample_submission.csv")
    MODEL_PATH = os.path.join(MODEL_DIR, "rf.pkl")
    OUT_PATH = os.path.join(OUT_DIR, "submission.csv")

    # ---- 모델 로드 ----
    print("Load model...")
    model = joblib.load(MODEL_PATH)
    print(f" OK. n_features={getattr(model, 'n_features_in_', '?')}")

    # ---- 테스트 데이터 로드 ----
    print("Load test data...")
    test = load_test(TEST_PATH)
    sub = load_sample_submission(SAMPLE_SUB_PATH)
    print(f" test={len(test)}  submission={len(sub)}")

    # ---- 전처리 (학습과 동일) ----
    print("Build features...")
    ids = test[ID_COL].tolist()
    X = build_features(test)
    print(f" features={X.shape[1]}")

    # ---- 예측 (제구 성공 확률) ----
    print("Inference model...")
    preds = model.predict_proba(X)[:, 1] if len(X) else []
    print(f" preds={len(preds)}")

    # ---- sample_submission 기반 결과 생성 ----
    print("Build submission...")
    sub = merge_predictions(sub, ids, preds)
    save_submission(OUT_PATH, sub)
    print(f"Saved: {OUT_PATH} (rows={len(sub)})")


if __name__ == "__main__":
    main()

import os
import zipfile
import sklearn
import pandas as pd
import numpy as np
import joblib
from google.colab import files

# 현재 코랩 환경의 sklearn 버전 확인
sklearn_version = sklearn.__version__
print(f"현재 Colab의 scikit-learn 버전: {sklearn_version}")

# 1. script.py 생성
script_code = """import os
import joblib
import pandas as pd

ID_COL = "row_id"
TARGET_COL = "control_success"

def load_test(path):
    df = pd.read_csv(path, encoding="utf-8-sig")
    if ID_COL not in df.columns:
        raise ValueError(f"test 데이터에 {ID_COL} 컬럼이 없음: {list(df.columns)[:5]}")
    return df

def load_sample_submission(path):
    df = pd.read_csv(path, encoding="utf-8-sig")
    if list(df.columns[:2]) != [ID_COL, TARGET_COL]:
        raise ValueError(f"sample_submission 컬럼이 ({ID_COL}, {TARGET_COL})이 아님: {list(df.columns)}")
    return df

def build_features(df):
    return df.drop(columns=[ID_COL])

def merge_predictions(sub, ids, preds):
    pred_map = dict(zip(ids, preds))
    values, n_missing = [], 0
    for rid, cur in zip(sub[ID_COL], sub[TARGET_COL]):
        p = pred_map.get(rid)
        if p is None:
            n_missing += 1
            values.append(cur)
        else:
            values.append(p)
    if n_missing:
        print(f"경고: 예측이 없어 placeholder를 유지한 row_id {n_missing}건")
    sub[TARGET_COL] = values
    return sub

def save_submission(path, sub):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    sub.to_csv(path, index=False, encoding="utf-8")

def main():
    TEST_DIR = "./data"
    MODEL_DIR = "./model"
    OUT_DIR = "./output"
    TEST_PATH = os.path.join(TEST_DIR, "test.csv")
    SAMPLE_SUB_PATH = os.path.join(TEST_DIR, "sample_submission.csv")
    MODEL_PATH = os.path.join(MODEL_DIR, "rf.pkl")
    OUT_PATH = os.path.join(OUT_DIR, "submission.csv")

    print("Load model...")
    model = joblib.load(MODEL_PATH)

    print("Load test data...")
    test = load_test(TEST_PATH)
    sub = load_sample_submission(SAMPLE_SUB_PATH)

    print("Build features...")
    ids = test[ID_COL].tolist()
    X = build_features(test)

    print("Inference model...")
    preds = model.predict_proba(X)[:, 1] if len(X) else []

    print("Build submission...")
    sub = merge_predictions(sub, ids, preds)
    save_submission(OUT_PATH, sub)
    print(f"Saved: {OUT_PATH} (rows={len(sub)})")

if __name__ == "__main__":
    main()
"""

with open("script.py", "w", encoding="utf-8") as f:
    f.write(script_code)

# 2. requirements.txt 에 현재 코랩 scikit-learn 버전을 명시하여 버전을 강제 일치시킴
requirements_code = f"""pandas==2.0.3
numpy==1.26.4
scikit-learn=={sklearn_version}
joblib==1.5.3
"""

with open("requirements.txt", "w", encoding="utf-8") as f:
    f.write(requirements_code)

# 3. submit.zip 새로 생성
zip_filename = 'submit.zip'
with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
    zipf.write('./model/rf.pkl', arcname='model/rf.pkl')
    zipf.write('script.py', arcname='script.py')
    zipf.write('requirements.txt', arcname='requirements.txt')

print("✅ 수정된 submit.zip 생성 완료! 다운로드를 시작합니다...")
files.download(zip_filename)

